# Generated by Django 6.0.3 on 2026-03-29 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('rent_adjustment', 'Rent Adjustment'), ('partial_payment', 'Partial Payment'), ('bond_deduction', 'Bond Deduction'), ('lease_termination', 'Lease Termination'), ('expense_update', 'Expense Update'), ('document_upload', 'Document Upload'), ('reminder_sent', 'Reminder Sent'), ('manual_status_change', 'Manual Status Change'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('tenant', 'Tenant'), ('owner', 'Owner')], max_length=20)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('reminder_type', models.CharField(choices=[('rent_due', 'Rent Due'), ('rent_overdue', 'Rent Overdue'), ('lease_expiry', 'Lease Expiry'), ('bond_deduction', 'Bond Deduction Summary'), ('custom', 'Custom')], max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('scheduled_send_time', models.DateTimeField()),
                ('sent_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='properties.lease')),
            ],
        ),
    ]
