# Generated by Django 6.0.3 on 2026-04-03 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonddeduction',
            name='expense',
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='financial_records/')),
                ('is_paid', models.BooleanField(default=False, help_text='For outgoing: has the owner paid this? For incoming: has payment been received?')),
                ('deduct_from_bond', models.BooleanField(default=False, help_text='Outgoing only: deduct this amount from bond at lease end settlement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_records', to='properties.lease')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='properties.property')),
                ('rent_obligation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_records', to='finance.rentobligation')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bonddeduction',
            name='financial_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.financialrecord'),
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
