# Generated by Django 6.0.3 on 2026-04-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_bonddeduction_expense_financialrecord_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialrecord',
            name='attachment',
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='drive_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
