# Generated by Django 6.0.3 on 2026-04-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='google_credentials',
            field=models.JSONField(blank=True, help_text='Stored OAuth credentials for Google Drive', null=True),
        ),
    ]
