# Generated by Django 6.0.3 on 2026-04-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_document_file_document_drive_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
